# Generated by Django 3.1 on 2020-08-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.TextField()),
                ('soyisim', models.TextField()),
                ('bolum', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ogretmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.TextField()),
                ('soyisim', models.TextField()),
                ('maas', models.TextField()),
            ],
        ),
    ]
